# Generated by Django 3.0.7 on 2020-06-17 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer_Serving_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'beer serving style',
                'verbose_name_plural': 'beer serving styles',
            },
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=50)),
                ('location_address', models.CharField(max_length=255)),
                ('brewery', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='cocktails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cocktail',
                'verbose_name_plural': 'cocktails',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_at'), descending=True, nulls_last=False),),
            },
        ),
        migrations.CreateModel(
            name='Cocktail_Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notchlistApi.Cocktail')),
            ],
            options={
                'verbose_name': 'cocktail ingredient',
                'verbose_name_plural': 'cocktails ingredients',
            },
        ),
        migrations.CreateModel(
            name='Drink_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'drink style',
                'verbose_name_plural': 'drink styles',
            },
        ),
        migrations.CreateModel(
            name='Glassware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='glassware')),
            ],
            options={
                'verbose_name': 'glassware',
                'verbose_name_plural': 'glasswares',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=50)),
                ('location_address', models.CharField(max_length=255)),
                ('winery', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('abv', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='beer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drink_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notchlistApi.Drink_Style')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wine_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wine',
                'verbose_name_plural': 'wines',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_at'), descending=True, nulls_last=False),),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cocktails', models.ManyToManyField(through='notchlistApi.Cocktail_Ingredient', to='notchlistApi.Cocktail')),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
            },
        ),
        migrations.AddField(
            model_name='drink_style',
            name='glassware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notchlistApi.Glassware'),
        ),
        migrations.AddField(
            model_name='cocktail_ingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notchlistApi.Ingredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(through='notchlistApi.Cocktail_Ingredient', to='notchlistApi.Ingredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=50)),
                ('location_address', models.CharField(max_length=255)),
                ('brewery', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('abv', models.CharField(max_length=10)),
                ('ibu', models.CharField(max_length=10)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='beer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beer_serving_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notchlistApi.Beer_Serving_Style')),
                ('drink_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notchlistApi.Drink_Style')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beer_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'beer',
                'verbose_name_plural': 'beers',
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_at'), descending=True, nulls_last=False),),
            },
        ),
    ]
