# Generated by Django 3.0.7 on 2020-06-23 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notchlistApi', '0002_auto_20200623_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beer_serving_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_style', to='notchlistApi.Beer_Serving_Style'),
        ),
    ]
