# Generated by Django 3.0.7 on 2020-06-24 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notchlistApi', '0005_auto_20200623_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='drink_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wine_drink_style', to='notchlistApi.Drink_Style'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='wine'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wine_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
